apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: crud-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-backend-deployment
  namespace: crud-app
  labels:
    app: crud-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-backend
  template:
    metadata:
      labels:
        app: crud-backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "crud-backend-role"
        vault.hashicorp.com/agent-inject-secret-db-credentials: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-db-credentials: |
          {{- with secret "internal/data/database/config" -}}
          export DB_USER="{{ .Data.data.username }}"
          export DB_PASSWORD="{{ .Data.data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: backend-api
          image: devopsflow999/crud-backend:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # This hooks up Vault variables directly to your 'npm run start' process
          command: ["/bin/sh", "-c"]
          args: ["source /vault/secrets/db-credentials && npm run start"]
          env:
            - name: DB_HOST
              value: "postgres-postgresql.postgresql.svc.cluster.local"
            - name: DB_NAME
              value: "app_production"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: crud-app
  labels:
    app: crud-backend
spec:
  selector:
    app: crud-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-web
  type: ClusterIP